[options]
admin_passwd = $pbkdf2-sha512$600000$U6o1xtjb./9fK2WMMUYopQ$S5Xcph.C68SKdynhu1ZhJEBEk4k6ADvvUwpivUIhQGdACpyOfN/EE8VlPk6o9WS7j.VzpsArE1SO1Z9OKTyxEw
db_port = 5432
db_user = odoo
db_password = odoo123
addons_path = D:\odoo19\odoo\addons,D:\odoo19\custom_addons
http_port = 8069
log_level = debug

